export const CONFIG = {
  tries: 6,
  language: 'English',
  wordLength: 5,
  author: 'Ootzk',
  authorWebsite: 'https://github.com/Ootzk/Wor-chain-dle',
  wordListSource: 'Original Wordle',
  wordListSourceLink: 'https://www.nytimes.com/games/wordle',
  googleAnalytics: '',
  shuffle: false,
  normalization: 'NFC',
  startDate: 'February 16, 2026 00:00:00',
  defaultLang: 'en',
  availableLangs: ['en'],
  escapeSpecialCharacters: true,
}
